### ISSUE TITLE
Event Screen UI Issues

### ISSUE THREAD

**Issue by Henansh721** [RahulSingh212/iiit-delhi-events#1]
The event description is appearing multiple times in the mobile application.
![WhatsApp Image 2023-11-26 at 01 42 04](https://github.com/RahulSingh212/iiit-delhi-events/assets/88682260/70db4121-a0a8-4648-9548-4c3ba9baefa1)

**Comment by Henansh721** [comment]
The event location text 
![WhatsApp Image 2023-11-26 at 02 16 59](https://github.com/RahulSingh212/iiit-delhi-events/assets/88682260/58dcacfc-4a4f-49b0-9e94-1ec633638564)
overflows in the mobile application.

**Comment by RahulSingh212** [comment]
Event description occurring multiple times fixed. Now it's only showing one time.
